### ISSUE TITLE
$.bbq.getState e.getState and $.bbq. in general

### ISSUE THREAD

**Issue by hasokeric** [cowboy/jquery-hashchange#12]
They all dont exist anymore since i updated so i had to return back to the old bbq :/

**Comment by hasokeric** [comment]
theyre all undefined :z

**Comment by hasokeric** [comment]
any updates

**Comment by petersendidit** [comment]
Think you are looking for: http://github.com/cowboy/jquery-bbq

**Comment by hasokeric** [comment]
your right. wow. tx

**Comment by hasokeric** [comment]
tx
