### ISSUE TITLE
jQuery 1.4.3 and BBQ

### ISSUE THREAD

**Issue by hasokeric** [cowboy/jquery-hashchange#14]
Is it just me or does bbq hashchange not work in 1.4.3... i just updated to 1.4.3 only and now all my hyperlinks are just regular hyperlinks... hashchange event is not fired.

**Comment by hasokeric** [comment]
looks like 1.4.3 makes 'a[href^=#]' not working anymore

**Comment by cowboy** [comment]
This appears to be a bug in jQuery 1.4.3 and not this plugin.

**Comment by hasokeric** [comment]
well the people in jquery irc channel said that it should be href='#' with single quotes... that helped... but in your example no quotes are used... so they must have liminated that  ? :P
