### ISSUE TITLE
Title changes in IE8

### ISSUE THREAD

**Issue by bobanj** [cowboy/jquery-hashchange#15]
Example:

```
   $('.maximize').live('click', function() {
         var el = $(this).parent().parent();
         var categoryID = el.attr('id').split('_')[1];
         $.bbq.pushState({category_id: categoryID});
    });
   $(window).bind('hashchange', function () {
         var category_id = $.bbq.getState('category_id');
         if (typeof(category_id) != "undefined") {
             maximizeCategory(categoryID);
         }
    });
```

I've also tried setting 
        window.location.hash = '';
Does the title needs to be changed explicitly? 
         document.title = "My Title";

**Comment by cowboy** [comment]
Yes, you need to set `document.title` explicitly. See this example:

http://benalman.com/code/projects/jquery-hashchange/examples/hashchange/

**Comment by bobanj** [comment]
Thank You for the fast reply :)
