### ISSUE TITLE
Safari 4 - Hash change event throws error after navigating to a page on a different domain

### ISSUE THREAD

**Issue by csytan** [cowboy/jquery-hashchange#2]
To reproduce (in Safari 4, OSX):
1. Visit http://benalman.com/code/projects/jquery-hashchange/examples/hashchange/ 
2. Click on the Test buttons to trigger hash change 
3. Visit http://google.com (or another domain) 
4. Click the back button several times. The first hash change will throw an error. 

The error returned is: 
  TypeError: Result of expression 'url' [undefined] is not an object.
  Line 91 on: jquery.ba-hashchange.js 

Cheers & Thanks for the great plugin

**Comment by csytan** [comment]
Updated version fixed this problem

**Comment by cowboy** [comment]
This has been fixed with the release of 1.2.

I've also submitted a bug report to [WebKit Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=34679) along with an [example page](http://benalman.com/code/projects/jquery-hashchange/examples/bug-safari-back-from-diff-domain/).
