### ISSUE TITLE
1.2 minified throws "K is not defined", similar error with non-minified

### ISSUE THREAD

**Issue by Marketera** [cowboy/jquery-hashchange#6]
See test at http://nathanbrauer.com
(Use Firebug to remove the comments allowing the js to be loaded. Currently, I'm using a simple workaround - so the page works as expected, but it's not using jquery-hashchange.)

**Comment by cowboy** [comment]
You need to use a newer version of jQuery. I recommend 1.4.2, but 1.3.2 will work as well!

**Comment by Marketera** [comment]
Whoops. Didn't realize the theme was sitting on such an old jQuery version.
Thanks :)
